// Generates web/map.ts: Singapore outline split into one Voronoi zone per NEA station.
// Run: node scripts/build-map.ts <ne_10m_admin_0_countries.geojson>
import { readFileSync, writeFileSync } from 'node:fs'
import { area, centroid, contains, project, simplify, toPath, voronoiCells } from './geometry.ts'
import type { Pt } from './geometry.ts'
import { REGION_CENTRES } from '../shared/regions.ts'
import { REGIONS } from '../shared/types.ts'

const TOLERANCE = 0.5
const r1 = (n: number) => Math.round(n * 10) / 10
const round = (p: Pt[]): Pt[] => p.map(([x, y]) => [r1(x), r1(y)])

const src = process.argv[2]
if (!src) throw new Error('usage: node scripts/build-map.ts <countries.geojson>')
const feature = JSON.parse(readFileSync(src, 'utf8')).features.find(
  (f: { properties: { ISO_A3?: string; ADM0_A3?: string } }) => f.properties.ISO_A3 === 'SGP' || f.properties.ADM0_A3 === 'SGP',
)
if (!feature) throw new Error('SGP feature not found')
const g = feature.geometry
const polys: number[][][][] = g.type === 'Polygon' ? [g.coordinates] : g.coordinates
const rings: Pt[][] = polys.map((p) => {
  const ring = p[0].map(([lon, lat]) => project(lon, lat))
  // GeoJSON rings repeat the first point at the end; ours don't.
  return ring.length > 1 && ring[0][0] === ring.at(-1)![0] && ring[0][1] === ring.at(-1)![1] ? ring.slice(0, -1) : ring
})
const main = rings.reduce((a, b) => (area(b) > area(a) ? b : a))
const outline = round(simplify(main, TOLERANCE))
console.log(`outline points: ${main.length} -> ${outline.length} (tolerance ${TOLERANCE})`)

const cells = voronoiCells(REGIONS.map((r) => project(REGION_CENTRES[r].lng, REGION_CENTRES[r].lat)), outline)
const zonePolys = {} as Record<string, Pt[]>
const labels = {} as Record<string, Pt>
REGIONS.forEach((r, i) => {
  const zone = round(cells[i])
  const c = REGION_CENTRES[r]
  const station = project(c.lng, c.lat)
  const mid = centroid(zone)
  zonePolys[r] = zone
  // Concave zones can put the centroid outside; fall back to the station.
  labels[r] = round([contains(zone, mid) ? mid : station])[0]
  console.log(`${r}: area ${area(zone).toFixed(0)}`)
})
console.log(`outline area: ${area(outline).toFixed(0)}`)

const xs = outline.map((p) => p[0])
const ys = outline.map((p) => p[1])
const minX = Math.min(...xs) - 4
const minY = Math.min(...ys) - 4
const viewBox = `${r1(minX)} ${r1(minY)} ${r1(Math.max(...xs) + 4 - minX)} ${r1(Math.max(...ys) + 4 - minY)}`
const zones = Object.fromEntries(REGIONS.map((r) => [r, toPath(zonePolys[r])]))

writeFileSync(
  new URL('../web/map.ts', import.meta.url),
  `// Generated by \`node scripts/build-map.ts <ne_10m_admin_0_countries.geojson>\` on ${new Date().toISOString().slice(0, 10)}.
// Source: Natural Earth 1:10m admin-0 countries (Singapore). Licence: Natural Earth, public domain.
// Do not edit by hand.
export const MAP: {
  viewBox: string
  outline: string
  outlinePoly: [number, number][]
  zones: Record<'north' | 'south' | 'east' | 'west' | 'central', string>
  zonePolys: Record<'north' | 'south' | 'east' | 'west' | 'central', [number, number][]>
  labels: Record<'north' | 'south' | 'east' | 'west' | 'central', [number, number]>
} = ${JSON.stringify({ viewBox, outline: toPath(outline), outlinePoly: outline, zones, zonePolys, labels })}
`,
)
